repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker

  - repo: local
    hooks:
      - id: format
        name: format
        entry: pw format
        language: script
        types: [ python ]
        pass_filenames: false

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: pw lint
        language: script
        types: [ python ]
        pass_filenames: false
